name: xcape
version: HEAD
summary: Modify keys to act as other keys
description: xcape allows you to use a modifier key as another key when pressed and released on its own. Note that it is slightly slower than pressing the original key, because the pressed event does not occur until the key is released. The default behaviour is to generate the Escape key when Left Control is pressed and released on its own. (If you don't understand why anybody would want this, I'm guessing that Vim is not your favourite text editor ;)
confinement: strict

apps:
  xcape:
    command: usr/bin/xcape
    plugs: [x11]

parts:
  xcape:
    plugin: make
    source: https://github.com/alols/xcape.git
    build-packages: [libx11-dev, libxtst-dev, libxi-dev]
